updating packer.yml

diff --git a/.github/workflows/packer.yml b/.github/workflows/packer.yml
--- a/.github/workflows/packer.yml
+++ b/.github/workflows/packer.yml
@@ -1,29 +1,17 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Packer CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
   pull_request:
     branches: [ "main" ]
-    
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "packer-check"
   packer-check:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      # Runs a single command using the runners shell
       - name: Install Packer
         run: |
           curl -O https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
@@ -31,14 +19,32 @@ jobs:
           sudo mv packer /usr/local/bin/packer
           packer version
 
-      # Runs a set of commands using the runners shell
       - name: Packer fmt
+        id: fmt
         run: |
           cd backend
+          git_diff_before=$(git diff)
           packer fmt packer.pkr.hcl
+          git_diff_after=$(git diff)
 
-      # Runs a set of commands using the runners shell
+          if [ "$git_diff_before" != "$git_diff_after" ]; then
+            echo "Packer fmt modified files. Please fix the formatting and commit the changes."
+            echo "exit_code=1" >> $GITHUB_OUTPUT
+          else
+            echo "Packer fmt did not modify any files."
+            echo "exit_code=0" >> $GITHUB_OUTPUT
+          fi
+
       - name: Packer validate
+        id: validate
         run: |
           cd backend
           packer validate packer.pkr.hcl
+          exit_code=$?
+          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
+
+      - name: Check exit codes
+        if: steps.fmt.outputs.exit_code != 0 || steps.validate.outputs.exit_code != 0
+        run: |
+          echo "Packer lint failed. Please fix the issues and try again."
+          exit 1
